// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
	"app-api/boot"
	"gorm.io/gorm"
)

const TableNameAdItem = "ad_items"

// AdItem mapped from table <ad_items>
type AdItem struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	Name      string    `gorm:"column:name;type:varchar(255);comment:广告名称" json:"name"`                           // 广告名称
	Title     string    `gorm:"column:title;type:varchar(255);comment:广告标题" json:"title"`                         // 广告标题
	Image     string    `gorm:"column:image;type:varchar(255);comment:广告图片" json:"image"`                         // 广告图片
	Content   string    `gorm:"column:content;type:text;comment:广告内容" json:"content"`                             // 广告内容
	URL       string    `gorm:"column:url;type:varchar(255);comment:广告链接" json:"url"`                             // 广告链接
	StartTime time.Time `gorm:"column:start_time;type:timestamp;comment:开始时间" json:"start_time"`                  // 开始时间
	EndTime   time.Time `gorm:"column:end_time;type:timestamp;comment:结束时间" json:"end_time"`                      // 结束时间
	Status    string    `gorm:"column:status;type:char(20);not null;default:N;comment:状态 N 隐藏-Y显示" json:"status"` // 状态 N 隐藏-Y显示
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                  // 更新时间
}

// TableName AdItem's table name
func (*AdItem) TableName() string {
	return TableNameAdItem
}

func (s *AdItem) AfterFind(tx *gorm.DB) (err error) {
	prefix := boot.Config.App.AssetUrl
	if s.Image != "" {
		s.Image = prefix + s.Image
	}

	return
}

