// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAdSpace = "ad_spaces"

// AdSpace mapped from table <ad_spaces>
type AdSpace struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:varchar(32);comment:广告位置" json:"name"`                            // 广告位置
	Key       string    `gorm:"column:key;type:varchar(32);comment:广告标识" json:"key"`                              // 广告标识
	Remark    string    `gorm:"column:remark;type:varchar(255);comment:备注说明" json:"remark"`                       // 备注说明
	Status    string    `gorm:"column:status;type:char(20);not null;default:N;comment:状态 N 隐藏-Y显示" json:"status"` // 状态 N 隐藏-Y显示
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                  // 更新时间
	Items     []*AdItem `gorm:"many2many:ad_space_item;joinForeignKey:space_id;joinReferences:item_id;" json:"items"`                                                            //  广告内容
}

// TableName AdSpace's table name
func (*AdSpace) TableName() string {
	return TableNameAdSpace
}
