// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;type:varchar(255);comment:图片名称" json:"name"`          // 图片名称
	URL          string    `gorm:"column:url;type:varchar(255);comment:URL" json:"url"`             // URL
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:归属用户ID" json:"user_id"`        // 归属用户ID
	Path         string    `gorm:"column:path;type:varchar(255);comment:存储路径" json:"path"`          // 存储路径
	Size         int64     `gorm:"column:size;type:bigint;comment:大小" json:"size"`                  // 大小
	Hash         string    `gorm:"column:hash;type:char(32);comment:图片hash" json:"hash"`            // 图片hash
	UUID         string    `gorm:"column:uuid;type:varchar(64);comment:UUID" json:"uuid"`           // UUID
	Extension    string    `gorm:"column:extension;type:varchar(32);comment:图片后缀" json:"extension"` // 图片后缀
	Mime         string    `gorm:"column:mime;type:varchar(255)" json:"mime"`
	Disk         string    `gorm:"column:disk;type:varchar(32);comment:上传驱动" json:"disk"`                      // 上传驱动
	DownloadLink string    `gorm:"column:download_link;type:varchar(255);comment:下载链接地址" json:"download_link"` // 下载链接地址
	ExpiredAt    *time.Time `gorm:"column:expired_at;type:timestamp;comment:过期时间" json:"expired_at"`            // 过期时间
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
