// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOption = "options"

// Option 配置表
type Option struct {
	ID    int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;type:varchar(255);not null;comment:配置标题" json:"name"`       // 配置标题
	Key   string `gorm:"column:key;type:varchar(32);primaryKey;comment:键名" json:"key"`          // 键名
	Value string `gorm:"column:value;type:text;not null;comment:键值" json:"value"`               // 键值
}

// TableName Option's table name
func (*Option) TableName() string {
	return TableNameOption
}
