// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:订单ID" json:"id"`  // 订单ID
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                      // 用户ID
	ClientID     string    `gorm:"column:client_id;type:varchar(36);comment:客户端ClientID" json:"client_id"`      // 客户端ClientID
	OrderNo      string    `gorm:"column:order_no;type:varchar(32);comment:订单编号" json:"order_no"`               // 订单编号
	OrderType    string    `gorm:"column:order_type;type:varchar(20);comment:订单类型" json:"order_type"`           // 订单类型
	PayType      string    `gorm:"column:pay_type;type:varchar(20);comment:支付方式 alipay wechat" json:"pay_type"` // 支付方式 alipay wechat
	PayOrderNo   string    `gorm:"column:pay_order_no;type:varchar(64);comment:支付订单号" json:"pay_order_no"`      // 支付订单号
	PayTime      *time.Time `gorm:"column:pay_time;type:timestamp;comment:支付时间" json:"pay_time"`                 // 支付时间
	ProductID    int64    `gorm:"column:product_id;type:bigint;comment:商品编号" json:"product_id"`           // 商品编号
	ProductCode  string    `gorm:"column:product_code;type:varchar(64);comment:商品编码" json:"product_code"`       // 商品编码
	ProductName  string    `gorm:"column:product_name;type:varchar(255);comment:商品名称" json:"product_name"`      // 商品名称
	ProductPrice float64   `gorm:"column:product_price;type:decimal(10,2);comment:商品价格" json:"product_price"`   // 商品价格
	Quantity     int32     `gorm:"column:quantity;type:int;not null;comment:购买数量" json:"quantity"`              // 购买数量
	Amount       float64   `gorm:"column:amount;type:decimal(10,2);comment:订单总金额" json:"amount"`                // 订单总金额
	PayAmount    float64   `gorm:"column:pay_amount;type:decimal(10,2);comment:支付金额" json:"pay_amount"`         // 支付金额
	PayQrcode    string    `gorm:"column:pay_qrcode;type:varchar(255);comment:二维码字符串" json:"pay_qrcode"`        // 二维码字符串
	Title        string `gorm:"column:title;type:varchar(32);comment:标题" json:"title"`      // 标题
	Description  string `gorm:"column:description;type:varchar(255);comment:备注" json:"description"` // 备注
	Status    string    `gorm:"column:status;type:varchar(20);default:pending;comment:订单状态\n'pending' => '待付款',\n'paid' => '已付款',\n'completed' => '完成',\n'canceled' => '已取消',\n'refunded' => '已退款'" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
	ExpiredAt time.Time `gorm:"column:expired_at;type:timestamp;comment:订单过期时间" json:"expired_at"` // 订单过期时间
	Extra        string `gorm:"column:extra;type:varchar(500);comment:标题" json:"extra"`      // 补充字段信息
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
