// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSearchLog = "search_logs"

// SearchLog mapped from table <search_logs>
type SearchLog struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Title     string    `gorm:"column:title;type:varchar(64);comment:搜索关键词" json:"title"` // 搜索关键词
	Count     int64     `gorm:"column:count;type:bigint;comment:搜索次数" json:"count"`       // 搜索次数
	Sort      int64     `gorm:"column:sort;type:bigint;comment:排序" json:"sort"`           // 排序
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName SearchLog's table name
func (*SearchLog) TableName() string {
	return TableNameSearchLog
}
