// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
	"app-api/boot"
	"gorm.io/gorm"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code         string    `gorm:"column:code;type:varchar(32);comment:任务唯一编号" json:"code"`                                        // 任务唯一编号
	Title        string    `gorm:"column:title;type:varchar(255);comment:任务标题" json:"title"`                                       // 任务标题
	LaunchTitle  string    `gorm:"column:launch_title;type:varchar(255);comment:启动按钮标题" json:"launch_title"`                       // 启动按钮标题
	LaunchURL    string    `gorm:"column:launch_url;type:varchar(255);comment:启动链接地址" json:"launch_url"`                             // 启动按钮标题
	LaunchType    string    `gorm:"column:launch_type;type:varchar(255);comment:启动链接方式" json:"launch_type"`                          // 启动链接方式
	CompletedTitle  string    `gorm:"column:completed_title;type:varchar(255);comment:完成任务标题" json:"completed_title"`                // 完成按钮标题
	Type         string    `gorm:"column:type;type:varchar(32);comment:任务类型 none-一次性,daily,weekly,monthly,none-无限制" json:"type"`  // 任务类型 none-一次性,daily,weekly,monthly,none-无限制
	Status       string    `gorm:"column:status;type:varchar(20);default:Y;comment:任务状态 Y-显示 N-隐藏" json:"status"`                  // 任务状态 Y-显示 N-隐藏
	AppStatus    string    `gorm:"column:app_status;type:varchar(20);default:Y;comment:任务状态 Y-显示 N-隐藏" json:"app_status"`          // App任务状态 Y-显示 N-隐藏
	RewardType   string    `gorm:"column:reward_type;type:varchar(32);comment:奖励类型" json:"reward_type"`                               // 奖励类型
	RewardAmount float64   `gorm:"column:reward_amount;type:decimal(10,4);comment:任务奖励数量" json:"reward_amount"`                    // 任务奖励数量
	RewardCount  int32     `gorm:"column:reward_count;type:int;comment:任务次数限制" json:"reward_count"`                                // 任务次数限制
	RewardIcon   string    `gorm:"column:reward_icon;type:varchar(255);comment:奖品图标" json:"reward_icon"`                           // 奖品图标
	Icon         string    `gorm:"column:icon;type:varchar(255);comment:任务图标" json:"icon"`                                         // 任务图标
	Description  string    `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`                             // 描述
	Content      string    `gorm:"column:content;type:text;comment:详情" json:"content"`                                             // 详情
	Payload      string    `gorm:"column:payload;type:longtext;comment:任务载荷数据" json:"payload"`                                     // 任务载荷数据
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`                                // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                                // 更新时间
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}

// 图片文件增加前缀
func (s *Task) AfterFind(tx *gorm.DB) (err error) {
	prefix := boot.Config.App.AssetUrl
	if s.Icon != "" {
		s.Icon = prefix + s.Icon
	}

	if s.RewardIcon != "" {
		s.RewardIcon = prefix + s.RewardIcon
	}

	return
}
