// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTaxonomy = "taxonomy"

// Taxonomy mapped from table <taxonomy>
type Taxonomy struct {
	ID          int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	ParentID    int64         `gorm:"column:parent_id;type:bigint unsigned;not null;comment:父级ID" json:"parent_id"`     // 父级ID
	Taxonomy    string        `gorm:"column:taxonomy;type:varchar(64);comment:category,navigation,doc" json:"taxonomy"`   // category,navigation,doc
	Name        string        `gorm:"column:name;type:varchar(255);comment:名称" json:"name"`                             // 名称
	Slug        string        `gorm:"column:slug;type:varchar(255);comment:Slug" json:"slug"`                             // Slug
	Order       int32         `gorm:"column:order;type:int;comment:排序" json:"order"`                                    // 排序
	Title       string        `gorm:"column:title;type:varchar(255);comment:标题" json:"title"`                           // 标题
	Keywords    string        `gorm:"column:keywords;type:varchar(255);comment:关键词" json:"keywords"`                    // 关键词
	Description string        `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`               // 描述
	Content     string        `gorm:"column:content;type:text;comment:详情" json:"content"`                               // 详情
	Status      string        `gorm:"column:status;type:char(10);default:Y;comment:显示状态 Y-显示 N-隐藏" json:"status"`       // 显示状态 Y-显示 N-隐藏
	Icon        string        `gorm:"column:icon;type:varchar(64);comment:图标" json:"icon"`                              // 图标
	CreatedAt   time.Time     `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt   time.Time     `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
	Items 		[]*AppTool     `gorm:"foreignkey:TaxonomyID" json:"items"`
	Meta        TaxonomyMeta  `gorm:"foreignKey:TaxonomyID" json:"meta"`
}

// TableName Taxonomy's table name
func (*Taxonomy) TableName() string {
	return TableNameTaxonomy
}
