// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTaxonomyMeta = "taxonomy_meta"

// TaxonomyMetum mapped from table <taxonomy_meta>
type TaxonomyMeta struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TaxonomyID  int64     `gorm:"column:taxonomy_id;type:bigint;comment:归类ID" json:"taxonomy_id"` // 归类ID
	Color       string `gorm:"column:color;type:varchar(32);comment:字体颜色" json:"color"`          // 字体颜色
	BgColor     string `gorm:"column:bg_color;type:varchar(32);comment:背景色彩" json:"bg_color"`    // 背景色彩
}

// TableName TaxonomyMetum's table name
func (*TaxonomyMeta) TableName() string {
	return TableNameTaxonomyMeta
}
