// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTool = "tools"

// Tool mapped from table <tools>
type Tool struct {
	ID          int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	TaxonomyID  int32     `gorm:"column:taxonomy_id;type:int;comment:归类ID" json:"taxonomy_id"`                         // 归类ID
	Name        string    `gorm:"column:name;type:varchar(64);comment:分类名称" json:"name"`                               // 分类名称
	Icon        string    `gorm:"column:icon;type:varchar(64);comment:工具图标" json:"icon"`                               // 工具图标
	Route       string    `gorm:"column:route;type:varchar(255);comment:路由" json:"route"`                              // 路由
	URI         string    `gorm:"column:uri;type:varchar(255);comment:路由地址" json:"uri"`                                // 路由地址
	Title       string    `gorm:"column:title;type:varchar(255);comment:标题" json:"title"`                              // 标题
	Keywords    string    `gorm:"column:keywords;type:varchar(255);comment:关键词" json:"keywords"`                       // 关键词
	Description string    `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`                  // 描述
	Content     string    `gorm:"column:content;type:text;comment:详情" json:"content"`                                  // 详情
	Subdomain   string    `gorm:"column:subdomain;type:char(10);default:N;comment:是否开启子域名  Y 开启 N 否" json:"subdomain"` // 是否开启子域名  Y 开启 N 否
	Status      string    `gorm:"column:status;type:char(10);default:N;comment:是否上线 Y 禁用 N 否" json:"status"`           // 是否上线 Y 禁用 N 否
	Order       int32     `gorm:"column:order;type:int;comment:排序" json:"order"`                                       // 排序
	Pv          int32     `gorm:"column:pv;type:int;comment:浏览量" json:"pv"`                                            // 浏览量
	Price       float64   `gorm:"column:price;type:decimal(10,2);default:0.00;comment:价格" json:"price"`                // 价格
	Version     string    `gorm:"column:version;type:varchar(64);comment:版本" json:"version"`                           // 版本
	Upgrade     string    `gorm:"column:upgrade;type:text;comment:升级日志" json:"upgrade"`                                // 升级日志
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`                     // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                     // 更新时间
}

// TableName Tool's table name
func (*Tool) TableName() string {
	return TableNameTool
}
