// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserStat = "user_stat"

// UserStat mapped from table <user_stat>
type UserStat struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID     int64     `gorm:"column:user_id;type:bigint;not null;comment:用户ID" json:"user_id"`          // 用户ID
	Code       string    `gorm:"column:code;type:varchar(32);comment:任务唯一编号" json:"code"`                  // 任务唯一编号
	TodayDate  int32     `gorm:"column:today_date;type:int;comment:今日" json:"today_date"`                  // 今日
	WeekDate   int32     `gorm:"column:week_date;type:int;comment:本周" json:"week_date"`                    // 本周
	MonthDate  int32     `gorm:"column:month_date;type:int;comment:本月" json:"month_date"`                  // 本月
	YearDate   int32     `gorm:"column:year_date;type:int;comment:今年" json:"year_date"`                    // 今年
	TodayCount int32     `gorm:"column:today_count;type:int;comment:今日完成次数" json:"today_count"`            // 今日完成次数
	WeekCount  int32     `gorm:"column:week_count;type:int;comment:本周完成次数" json:"week_count"`              // 本周完成次数
	MonthCount int32     `gorm:"column:month_count;type:int;comment:本月完成次数" json:"month_count"`            // 本月完成次数
	YearCount  int32     `gorm:"column:year_count;type:int;comment:今年完成次数" json:"year_count"`              // 今年完成次数
	Count      int32     `gorm:"column:count;type:int;comment:总共完成次数" json:"count"`                        // 总共完成次数
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`          // 更新时间
}

// TableName UserStat's table name
func (*UserStat) TableName() string {
	return TableNameUserStat
}
