// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserActivityLog = "user_activity_logs"

// UserActivityLog mapped from table <user_activity_logs>
type UserActivityLog struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`   
	UUID         string    `gorm:"column:uuid;type:varchar(36);comment:UUID" json:"uuid"`                                                    // ID
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                                                                    // 用户ID
	Code         string    `gorm:"column:code;type:varchar(32);comment:操作代码" json:"code"`                                                                     // 操作代码
	Amount       float64   `gorm:"column:amount;type:decimal(10,2);default:0.00;comment:扣费金额" json:"amount"`                                                  // 扣费金额
	Title        string    `gorm:"column:title;type:varchar(32);comment:标题" json:"title"`                                                                     // 标题
	Description  string    `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`                                                        // 描述
	ContentType  string    `gorm:"column:content_type;type:varchar(32);comment:响应内容类型 text,image,audio,video" json:"content_type"`                            // 响应内容类型 text,image,audio,video
	Content      string    `gorm:"column:content;type:text;comment:用户展示结果内容" json:"content"`                                                                  // 用户展示结果内容
	FormSchemas  string    `gorm:"column:form_schemas;type:text;comment:表单信息" json:"form_schemas"`                                                            // 表单信息
	RequestBody  string    `gorm:"column:request_body;type:text;comment:请求内容" json:"request_body"`                                                            // 请求内容
	ResponseBody string    `gorm:"column:response_body;type:text;comment:响应内容" json:"response_body"`                                                          // 响应内容
	Status       string    `gorm:"column:status;type:varchar(32);default:pending;comment:状态: pending-已提交, fail-处理失败, success-成功, refunded-已退费" json:"status"` // 状态: pending-已提交, fail-处理失败, success-成功, refunded-已退费
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserActivityLog's table name
func (*UserActivityLog) TableName() string {
	return TableNameUserActivityLog
}
