// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserWechatApp = "user_wechat_app"

// UserWechatApp mapped from table <user_wechat_app>
type UserWechatApp struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;type:bigint;comment:关联用户ID" json:"user_id"`                        // 关联用户ID
	Openid    string    `gorm:"column:openid;type:varchar(255);comment:微信小程序openid" json:"openid"`               // 微信小程序openid
	Unionid   string    `gorm:"column:unionid;type:varchar(255);default:0;comment:微信开放平台unionid" json:"unionid"` // 微信开放平台unionid
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserWechatApp's table name
func (*UserWechatApp) TableName() string {
	return TableNameUserWechatApp
}
