// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserBalanceLog = "user_balance_logs"

// UserBalanceLog mapped from table <user_balance_logs>
type UserBalanceLog struct {
	ID         int64    `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64    `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"` // 用户ID
	Code      string   `gorm:"column:code;type:varchar(32);comment:扣费项目代码" json:"code"`   // 扣费项目代码
	Title      string   `gorm:"column:title;type:varchar(255);comment:名称" json:"title"`   // 名称
	Type       string   `gorm:"column:type;type:varchar(32);comment:increase-增加 decrease-减少\n\n" json:"type"`
	Balance    float64  `gorm:"column:balance;type:decimal(10,2);comment:当前余额" json:"balance"` // 当前余额
	Amount     float64  `gorm:"column:amount;type:decimal(10,2);comment:消费金额" json:"amount"`   // 消费金额
	Description string  `gorm:"column:description;type:varchar(255);comment:备注" json:"description"`      // 备注
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserBalanceLog's table name
func (*UserBalanceLog) TableName() string {
	return TableNameUserBalanceLog
}
