// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID              int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MMID            int64     `gorm:"column:mmid;type:bigint" json:"mmid"`
	Name            string    `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Email           string    `gorm:"column:email;type:varchar(255);not null" json:"email"`
	EmailVerifiedAt *time.Time `gorm:"column:email_verified_at;type:timestamp;" json:"email_verified_at"`
	Username        string    `gorm:"column:username;type:varchar(255)" json:"username"`
	Password        string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	RememberToken   string    `gorm:"column:remember_token;type:varchar(100)" json:"remember_token"`
	Balance         float64   `gorm:"column:balance;type:decimal(10,2);default:0.00;comment:账户余额" json:"balance"`    // 账户余额
	Score           int64     `gorm:"column:score;type:bigint;comment:积分" json:"score"`                              // 积分
	Point           int64     `gorm:"column:point;type:bigint;comment:点数" json:"point"`                              // 点数
	Reward          float64   `gorm:"column:reward;type:decimal(10,2);default:0.00;comment:奖励金额" json:"reward"`    // 奖励金额
	Gender          string    `gorm:"column:gender;type:char(10);comment:性别 Female-女 Male-男性" json:"gender"`         // 性别 Female-女 Male-男性
	IsAdmin         string    `gorm:"column:is_admin;type:char(10);default:N;comment:是否管理员 Y-是 N-否" json:"is_admin"` // 是否管理员 Y-是 N-否
	Avatar          string    `gorm:"column:avatar;type:varchar(255);comment:头像" json:"avatar"`                      // 头像
	Website         string    `gorm:"column:website;type:varchar(255);comment:个人网站" json:"website"`                  // 个人网站
	Bio             string    `gorm:"column:bio;type:varchar(255);comment:个人介绍" json:"bio"`                          // 个人介绍
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
	VIP             UserVip   `gorm:"foreignKey:UserID" json:"vip"`
	Meta            UserMeta  `gorm:"foreignKey:UserID" json:"meta"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
