// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserPaymentAccount = "user_payment_account"

// UserPaymentAccount mapped from table <user_payment_account>
type UserPaymentAccount struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`
	PayType      string    `gorm:"column:pay_type;type:varchar(32);comment:收款方式" json:"pay_type"`
	Account      string    `gorm:"column:account;type:varchar(255);comment:收款账号" json:"account"`
	Name         string    `gorm:"column:name;type:varchar(32);comment:收款人姓名" json:"name"`
	BankName     string    `gorm:"column:bank_name;type:varchar(64);comment:银行名称" json:"bank_name"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserPaymentAccount's table name
func (*UserPaymentAccount) TableName() string {
	return TableNameUserPaymentAccount
}
