// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserTransfer = "user_transfer"

// UserTransfer 用户提现转账
type UserTransfer struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                                      // 用户ID
	Amount     float64   `gorm:"column:amount;type:decimal(10,2);comment:提现转账金额" json:"amount"`                               // 提现转账金额
	Account    string    `gorm:"column:account;type:varchar(255);comment:收款账号" json:"account"`                                // 收款账号
	Name       string    `gorm:"column:name;type:varchar(32);comment:真实姓名" json:"name"`                                       // 真实姓名
	OrderNo    string    `gorm:"column:order_no;type:varchar(64);comment:转账单号" json:"order_no"`                               // 转账单号
	PayType    string    `gorm:"column:pay_type;type:varchar(32);comment:收款方式 wechat;alipay" json:"pay_type"`                 // 收款方式 wechat;alipay
	PayOrderNo string    `gorm:"column:pay_order_no;type:varchar(64);comment:支付单号" json:"pay_order_no"`                       // 支付单号
	Status     string    `gorm:"column:status;type:varchar(32);default:pending;comment:转账状态 pending,paid,fail" json:"status"` // 转账状态 pending,paid,fail
	PayTime    *time.Time `gorm:"column:pay_time;type:timestamp;comment:转账时间" json:"pay_time"`                                 // 转账时间
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserTransfer's table name
func (*UserTransfer) TableName() string {
	return TableNameUserTransfer
}
