// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserMeta = "user_meta"

// UserMeta mapped from table <user_meta>
type UserMeta struct {
	ID           int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64  `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                    // 用户ID
	InviteQrcode string `gorm:"column:invite_qrcode;type:varchar(255);comment:邀请二维码" json:"invite_qrcode"` // 邀请二维码
	InviteID     int64  `gorm:"column:invite_id;type:bigint;comment:邀请码MMID" json:"invite_id"`             // 邀请码MMID
}

// TableName UserMeta's table name
func (*UserMeta) TableName() string {
	return TableNameUserMeta
}
