// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserVip = "user_vip"

// UserVip mapped from table <user_vip>
type UserVip struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                        // 用户ID
	Active     string    `gorm:"column:active;type:varchar(32);default:N;comment:是否有效 Y-有效 N-过期" json:"active"` // 是否有效 Y-有效 N-过期
	ExpireTime time.Time `gorm:"column:expire_time;type:timestamp;comment:会员到期时间" json:"expire_time"`           // 会员到期时间
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserVip's table name
func (*UserVip) TableName() string {
	return TableNameUserVip
}
