// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserInviteLog = "user_invite_logs"

// UserInvite mapped from table <user_invite>
type UserInviteLog struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:邀请人UID" json:"user_id"`                 // 邀请人UID
	InviteUserID int64     `gorm:"column:invite_user_id;type:bigint;comment:被邀人UID" json:"invite_user_id"`   // 被邀人UID
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
	User         User      `gorm:"foreignKey:UserID" json:"user"`
}

// TableName UserInvite's table name
func (*UserInviteLog) TableName() string {
	return TableNameUserInviteLog
}
