// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserCheckIn = "user_check_in"

// UserCheckIn mapped from table <user_check_in>
type UserCheckIn struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID    int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"`                   // 用户ID
	Count     int32     `gorm:"column:count;type:int unsigned;comment:连续签到次数" json:"count"`               // 连续签到次数
	Date      int32     `gorm:"column:date;type:int;comment:签到日期 格式20250101" json:"date"`                 // 签到日期 格式20250101
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`          // 更新时间
}

// TableName UserCheckIn's table name
func (*UserCheckIn) TableName() string {
	return TableNameUserCheckIn
}
