// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserRewardLog = "user_reward_logs"

// UserRewardLog mapped from table <user_reward_logs>
type UserRewardLog struct {
	ID     int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID int64 `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id"` // 用户ID
	/*
		操作类型 increase-增加 decrease-减少

	*/
	Type        string    `gorm:"column:type;type:varchar(32);comment:操作类型 increase-增加 decrease-减少\n" json:"type"`
	Code        string    `gorm:"column:code;type:varchar(32);comment:奖金来源代码" json:"code"`                  // 奖金来源代码
	Amount      float64   `gorm:"column:amount;type:decimal(10,2);default:0.00;comment:奖金数量" json:"amount"` // 奖金数量
	Title       string    `gorm:"column:title;type:varchar(32);comment:标题" json:"title"`                    // 标题
	Description string    `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`       // 描述
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UserRewardLog's table name
func (*UserRewardLog) TableName() string {
	return TableNameUserRewardLog
}
